platform :ios, ‘8.0’

target ‘Parking’ do

pod 'AFNetworking'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'ZBarSDK'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'AMapNavi'
pod 'PGDatePicker'
end
